# Generated by Django 3.1.2 on 2020-10-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdFund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproject',
            name='fund_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='newproject',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
