# Generated by Django 3.1.2 on 2020-10-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdFund', '0002_auto_20201014_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
        migrations.AddField(
            model_name='newproject',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
