# Generated by Django 3.1.2 on 2020-10-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdFund', '0003_auto_20201017_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproject',
            name='username',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
