# Generated by Django 3.1.2 on 2020-10-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrowdFund', '0006_auto_20201018_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
    ]
