# Generated by Django 3.1.2 on 2020-10-18 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CrowdFund', '0007_remove_donor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproject',
            name='donor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
